# Generated by Django 4.2.2 on 2023-06-29 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0004_alter_like_like_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
