# Generated by Django 4.2.2 on 2023-06-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0006_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='owner',
        ),
    ]
